/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData media_record =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData media_previous =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData media_shuffle =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData media_stop =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chevron_left =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData media_next =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData media_pause =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData media_play =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData volume_full =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData volume_low =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData volume_medium =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData volume_off =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData pulse = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData media_loop =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData clockwise =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData short_text =
      const IconData(0xe812, fontFamily: _kFontFam);
}
